FORMAT: 1A
HOST: https://localhost:8080/

# HouseMate API

HouseMate is a web API that allows users to view and create listings for houses and appartaments.

##  Posts Collection [/posts]

### List All Posts [GET]

+ Response 200 (application/json)

        [
            {
                "_id":"628099dc6824befa6e372e2a",
                "title":"annuncio",
                "app_id":1,
                "location":"/api/v1/posts/1"
            },
            {
                "_id":"62809a9b6824befa6e372e2b",
                "title":"annuncio_prova",
                "app_id":2,
                "location":"/api/v1/posts/2"
            },
            {
                "_id":"62809b246824befa6e372e2d",
                "title":"annuncio_prova",
                "app_id":3,
                "location":"/api/v1/posts/3"
            }
        ]
        
### Delete All Posts [DELETE]
+ Response 405 (application/json)

            {
                "Method Not Allowed"
            }

### Put A List Of Posts [PUT]
+ Response 405 (application/json)

            {
                "Method Not Allowed"
            }

### Single Post [/post/:id]        
        
### Fetch one post [GET]

+ Response 200 (application/json)

        {
            "_id":"628099dc6824befa6e372e2a",
            "title":"annuncio",
            "app_id":1
        }

### Coming Soon [POST]

You may create a new listing using this action. It takes a JSON
object containing all the listing parameters and adds the field to
the database.

+ Request (application/json)

        {
            "title": "Stanza singola per studenti"
        }

+ Response 201 (application/json)

    + Headers

            Location: /listings/1

    + Body

            {
                "title": "Stanza singola per studenti"
            }
            
##  User Collection [/users]